// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-W9usR5i5r_pzUw7WsBFrdFMiexsjdRc',
    appId: '1:737975083606:web:9ddb6746aced31a47f11f7',
    messagingSenderId: '737975083606',
    projectId: 'remind-memo-1b0ef',
    authDomain: 'remind-memo-1b0ef.firebaseapp.com',
    storageBucket: 'remind-memo-1b0ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQpvNYdtJWzRmZiGxbFvB2zC-DWZAiy5c',
    appId: '1:737975083606:android:a0d5208c13bdbf437f11f7',
    messagingSenderId: '737975083606',
    projectId: 'remind-memo-1b0ef',
    storageBucket: 'remind-memo-1b0ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi5qLUzrTqztIRVFuSYVKX0vAnw2BuT9E',
    appId: '1:737975083606:ios:c7b05c356e62c8ce7f11f7',
    messagingSenderId: '737975083606',
    projectId: 'remind-memo-1b0ef',
    storageBucket: 'remind-memo-1b0ef.appspot.com',
    iosClientId: '737975083606-jspsag4jfgo7i2siie69oo61g3m6rtnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi5qLUzrTqztIRVFuSYVKX0vAnw2BuT9E',
    appId: '1:737975083606:ios:3c01eda1b6ad3d4d7f11f7',
    messagingSenderId: '737975083606',
    projectId: 'remind-memo-1b0ef',
    storageBucket: 'remind-memo-1b0ef.appspot.com',
    iosClientId: '737975083606-vr46j6qhk38rtladuendsbs9fqm0rcsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
